version: '3.8'
services:
  pg-db:
    container_name: pg-db
    profiles: [ "db" ]
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  pg-admin:
    container_name: pg-admin
    profiles: [ "db" ]
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - pg-admin:/var/lib/pgadmin


volumes:
  pg-data:
  pg-admin:
